# Generated by Django 4.0.4 on 2022-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(auto_created=True)),
                ('song_name', models.FileField(blank=True, null=True, upload_to='media/')),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
