# Generated by Django 4.0.4 on 2022-05-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_name',
            field=models.FileField(blank=True, default=4, upload_to='media/'),
            preserve_default=False,
        ),
    ]
