# Generated by Django 4.0.4 on 2022-05-09 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_songs_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='uploaded_time',
            field=models.DateTimeField(auto_created=datetime.datetime(2022, 5, 9, 1, 51, 8, 492664)),
        ),
    ]
